### ISSUE TITLE
data in google drive is hard to download

### ISSUE THREAD

**Issue by zhangchenghua123** [YiwuZhong/Sub-GC#1]
hello ,coco_sg_output_64 is hard to download from google drive.Can you offer other ways to download?

**Comment by YiwuZhong** [comment]
Thanks for your interest in our work. I've tried several times downloading the data in different desktops and the data was successfully downloaded. You can try downloading the data again with a stable network connection.

**Comment by Zora-zjj** [comment]
I have the same problem with flickr30k_sg_output_64.zip, even data about coco has download,  Is there any other way to download flickr30k_sg_output_64.zip ??? Thankyou everymuch!

**Comment by YiwuZhong** [comment]
Thanks for your interest in our work. Google Drive might be the only way we can share the files. Since you have successfully downloaded COCO, Flick should be also downloadable. Sometimes the network isn't stable. You can try a few more times.

**Comment by Zora-zjj** [comment]
Thanks for you reply😊

发自我的iPhone


------------------ Original ------------------
From: Yiwu Zhong ***@***.***&gt;
Date: Thu,Apr 1,2021 10:35 PM
To: YiwuZhong/Sub-GC ***@***.***&gt;
Cc: Zora-zjj ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [YiwuZhong/Sub-GC] data in google drive is hard to download (#1)





 
Thanks for your interest in our work. Google Drive might be the only way we can share the files. Since you have successfully downloaded COCO, Flick should be also downloadable. Sometimes the network isn't stable. You can try a few more times.
