### ISSUE TITLE
how to use myself dataset？

### ISSUE THREAD

**Issue by zxh19976666** [YiwuZhong/Sub-GC#7]
thanks your great work sir！  but I want to use myself dataset？ could  you help me sir？ plz ！thanks！

**Comment by YiwuZhong** [comment]
Since this work was trained and evaluated on the standard image captioning benchmark (e.g., COCO Caption and Flickr30k), we don't plan to provide code for custom dataset. 

PS: If you want to build a captioning model on your own dataset, you will need to process the captions into the labels in the same format as COCO/Flickr30k datasets. Also, you have to obtain the region features from the object detector, the scene graphs from Motif-Net, and the sampled sub-graphs for all the images in your dataset.

**Comment by zxh19976666** [comment]
thank you for your reply sir！
